-- Script de Restore do Backup
-- Gerado em: 20260116_101317

-- EQUIPAMENTOS
INSERT INTO equipamento (id_interno, id_publico, tipo, marca, modelo, num_serie, data_aquisicao, localizacao, status, responsavel, ultima_manutencao, valor, observacoes, SPE, termo_pdf_path) VALUES ('1', 'PAT-001', 'Notebook', 'Dell', 'Inspiron 15 3520', 'FYD4R54', '2024-01-10', 'Sede', 'Em uso', 'Nivaldo Xavier', NULL, '2600.0', 'Novo - Contabilidade 1', 'ADMINISTRAÇÃO SEDE TERRANO', '');
INSERT INTO equipamento (id_interno, id_publico, tipo, marca, modelo, num_serie, data_aquisicao, localizacao, status, responsavel, ultima_manutencao, valor, observacoes, SPE, termo_pdf_path) VALUES ('2', 'PAT-002', 'Notebook', 'Dell', 'G15 5530', '2318679F-FA4A-48CC-B0CB-0E10D39F73AA', '2024-01-10', 'Sede', 'Em uso', 'Mauro Craveiro', NULL, '4000.0', 'Novo - Controladoria', 'ADMINISTRAÇÃO SEDE TERRANO', NULL);
INSERT INTO equipamento (id_interno, id_publico, tipo, marca, modelo, num_serie, data_aquisicao, localizacao, status, responsavel, ultima_manutencao, valor, observacoes, SPE, termo_pdf_path) VALUES ('3', 'PAT-003', 'Notebook', 'Dell', 'Vostro 5470', '605FEA9D-7D8D-4905-BB79-2B0FFB22E56E', NULL, 'Chapadao do Ceu', 'Em uso', 'Dayara de Souza', NULL, '1800.0', 'Usado - Marketing 5', 'FLOR DA TERRA - CHAPADAO DO CEU SPE LTDA', 'PAT-003.pdf');
INSERT INTO equipamento (id_interno, id_publico, tipo, marca, modelo, num_serie, data_aquisicao, localizacao, status, responsavel, ultima_manutencao, valor, observacoes, SPE, termo_pdf_path) VALUES ('4', 'PAT-004', 'Notebook', 'Lenovo', 'IdeaPad 3 15ALC6', '57C83FD4-5EE3-4D1E-8B17-AF53A6FBEAE3', NULL, 'Engenharia', 'Em uso', 'João Pedro Craveiro', '2025-02-19', '1800.0', 'Usado - Engenharia 2', 'SPE REUNIDAS PINUS EMPREENDIMENTOS IMOBILIARIOS LT', NULL);
INSERT INTO equipamento (id_interno, id_publico, tipo, marca, modelo, num_serie, data_aquisicao, localizacao, status, responsavel, ultima_manutencao, valor, observacoes, SPE, termo_pdf_path) VALUES ('5', 'PAT-005', 'Notebook', 'Dell', 'Inspiron 7348', 'FA6C76A0-F108-49D0-9FBF-4FC66106E497', NULL, 'Marketing', 'Em uso', 'Érika Santana', '2025-03-19', '1800.0', 'Usado - Marketing 7', 'SPE LARANJEIRAS EMPREENDIMENTOS LTDA', 'PAT-005.pdf');
INSERT INTO equipamento (id_interno, id_publico, tipo, marca, modelo, num_serie, data_aquisicao, localizacao, status, responsavel, ultima_manutencao, valor, observacoes, SPE, termo_pdf_path) VALUES ('6', 'PAT-006', 'Notebook', 'Lenovo', '82VY', 'PE0CHFX2', NULL, 'Marketing', 'Em uso', 'Dioni Quedes Vieira', '2025-03-01', '2300.0', 'Semi-novo - Marketing 4', 'ADMINISTRAÇÃO SEDE TERRANO', 'PAT-006.pdf');
INSERT INTO equipamento (id_interno, id_publico, tipo, marca, modelo, num_serie, data_aquisicao, localizacao, status, responsavel, ultima_manutencao, valor, observacoes, SPE, termo_pdf_path) VALUES ('7', 'PAT-007', 'Notebook', 'Dell', 'Inspiron 15 3520', 'JF24R54', '2024-10-07', 'Marketing', 'Em uso', 'Hanna Karoline Lopes Souza', '2025-06-03', '3162.0', 'Novo - Marketing 3', 'TERRANO MARA ROSA', 'PAT-007.pdf');
INSERT INTO equipamento (id_interno, id_publico, tipo, marca, modelo, num_serie, data_aquisicao, localizacao, status, responsavel, ultima_manutencao, valor, observacoes, SPE, termo_pdf_path) VALUES ('8', 'PAT-008', 'Notebook', 'Dell', 'G15 5530', 'F9BWQ74', '2025-05-23', 'Sede', 'Em uso', 'Vinícius Prados', '2025-07-15', '7899.0', 'Novo - Controladoria', 'SPE GOIANIRA EMPREENDIMENTOS IMOBILIARIOS LTDA', 'PAT-008.pdf');
INSERT INTO equipamento (id_interno, id_publico, tipo, marca, modelo, num_serie, data_aquisicao, localizacao, status, responsavel, ultima_manutencao, valor, observacoes, SPE, termo_pdf_path) VALUES ('9', 'PAT-009', 'Notebook', 'Dell', 'Inspiron 14 7440', 'D5R0D64', '2024-11-01', 'Sede', 'Em uso', 'Eduardo De Carvalho Craveiro', '2025-06-09', '6997.0', 'Novo - Diretoria', 'TERRANO FLOR DA TERRA PARTICIPACOES', NULL);
INSERT INTO equipamento (id_interno, id_publico, tipo, marca, modelo, num_serie, data_aquisicao, localizacao, status, responsavel, ultima_manutencao, valor, observacoes, SPE, termo_pdf_path) VALUES ('10', 'PAT-010', 'Notebook', 'Dell', 'Inspiron 15 3520', 'BNZR194', '2025-06-16', 'Financeiro', 'Em uso', 'Marcella Naciff', '2025-07-01', '3113.0', 'Novo - Financeiro 1', 'Terrano Rio Verde', NULL);
INSERT INTO equipamento (id_interno, id_publico, tipo, marca, modelo, num_serie, data_aquisicao, localizacao, status, responsavel, ultima_manutencao, valor, observacoes, SPE, termo_pdf_path) VALUES ('11', 'PAT-011', 'Notebook', 'Accer', 'Nitro V15', 'NHQQDAL008508019DFZ00', '2025-06-10', 'Marketing', 'Em uso', 'Jony Clay Gomes Ribeiro Junior', '2025-07-01', '5910.0', 'Novo - Marketing 1', 'SPE GOIANIRA EMPREENDIMENTOS IMOBILIARIOS LTDA', 'PAT-011.pdf');
INSERT INTO equipamento (id_interno, id_publico, tipo, marca, modelo, num_serie, data_aquisicao, localizacao, status, responsavel, ultima_manutencao, valor, observacoes, SPE, termo_pdf_path) VALUES ('12', 'PAT-012', 'Notebook', 'Accer', 'Nitro V15', 'NHQQDAL008508019E69Z00', '2025-06-10', 'Marketing', 'Em uso', 'Bárbara Jaques', '2025-07-01', '5910.0', 'Novo - Marketing 2', 'SPE GOIANIRA EMPREENDIMENTOS IMOBILIARIOS LTDA', 'PAT-012.pdf');
INSERT INTO equipamento (id_interno, id_publico, tipo, marca, modelo, num_serie, data_aquisicao, localizacao, status, responsavel, ultima_manutencao, valor, observacoes, SPE, termo_pdf_path) VALUES ('13', 'PAT-013', 'Notebook', 'Dell', 'Inspiron 15 3520', 'C62ZGB4', '2025-07-09', 'Financeiro', 'Em uso', 'Cristine Prego Maciel', '2025-07-15', '4176.0', 'Novo - Financeiro 3', 'SPE MARA ROSA EMPREENDIMENTOS IMOBILIÁRIOS LTDA', NULL);
INSERT INTO equipamento (id_interno, id_publico, tipo, marca, modelo, num_serie, data_aquisicao, localizacao, status, responsavel, ultima_manutencao, valor, observacoes, SPE, termo_pdf_path) VALUES ('14', 'PAT-014', 'Notebook', 'Dell', 'Inspiron 15 3520', '932ZGB4', '2025-07-09', 'Financeiro', 'Em uso', 'Cleudimar Mendes Moreira', '2025-07-20', '4176.0', 'Novo - Financeiro 4', 'SPE MARA ROSA EMPREENDIMENTOS IMOBILIÁRIOS LTDA', NULL);
INSERT INTO equipamento (id_interno, id_publico, tipo, marca, modelo, num_serie, data_aquisicao, localizacao, status, responsavel, ultima_manutencao, valor, observacoes, SPE, termo_pdf_path) VALUES ('15', 'PAT-015', 'Notebook', 'Dell', 'Inspiron 15 3520', 'C32ZGB4', '2025-07-09', 'Financeiro', 'Em uso', 'Ricardo De Assis Mesquita', '2025-07-20', '4000.0', 'Novo - Financeiro 5', 'SPE MARA ROSA EMPREENDIMENTOS IMOBILIÁRIOS LTDA', NULL);
INSERT INTO equipamento (id_interno, id_publico, tipo, marca, modelo, num_serie, data_aquisicao, localizacao, status, responsavel, ultima_manutencao, valor, observacoes, SPE, termo_pdf_path) VALUES ('16', 'PAT-016', 'Celular', 'Samsung', 'Galaxy A06', '352884314543654', '2025-07-11', 'Marketing', 'Em uso', 'Diego Brito Vieira', '2025-07-20', '604.0', 'Novo - Marketing C1', 'SPE MARA ROSA EMPREENDIMENTOS IMOBILIÁRIOS LTDA', 'PAT-016.pdf');
INSERT INTO equipamento (id_interno, id_publico, tipo, marca, modelo, num_serie, data_aquisicao, localizacao, status, responsavel, ultima_manutencao, valor, observacoes, SPE, termo_pdf_path) VALUES ('17', 'PAT-017', 'Notebook', 'Dell', 'Inspiron 14 5000', 'CZWQ172', '1900-01-01', 'Marketing', 'Em uso', 'Alex Motta da Cruz', '2025-07-18', '2500.0', 'Usado - Marketing 6', 'SPE MARA ROSA EMPREENDIMENTOS IMOBILIÁRIOS LTDA', 'PAT-017.pdf');
INSERT INTO equipamento (id_interno, id_publico, tipo, marca, modelo, num_serie, data_aquisicao, localizacao, status, responsavel, ultima_manutencao, valor, observacoes, SPE, termo_pdf_path) VALUES ('18', 'PAT-018', 'Notebook', 'Accer', 'Nitro V15', 'NHQQDAL008438018B69Z00', '2025-07-09', 'Engenharia', 'Em uso', 'Gilson Campos D'Antônio', '2025-07-21', '5140.0', 'Novo - Engenharia 1', 'SPE MARA ROSA EMPREENDIMENTOS IMOBILIÁRIOS LTDA', NULL);
INSERT INTO equipamento (id_interno, id_publico, tipo, marca, modelo, num_serie, data_aquisicao, localizacao, status, responsavel, ultima_manutencao, valor, observacoes, SPE, termo_pdf_path) VALUES ('19', 'PAT-019', 'Outro', 'TCL', 'Android TV 32"', 'S5400AF', '2025-07-11', 'Diretoria', 'Em uso', 'Terrano - ADM', '2025-07-15', '997.0', 'Novo - TV1', 'SPE MARA ROSA EMPREENDIMENTOS IMOBILIÁRIOS LTDA', NULL);
INSERT INTO equipamento (id_interno, id_publico, tipo, marca, modelo, num_serie, data_aquisicao, localizacao, status, responsavel, ultima_manutencao, valor, observacoes, SPE, termo_pdf_path) VALUES ('20', 'PAT-020', 'Notebook', 'Dell', 'Inspiron 15 3520', 'HYZR194', '2025-06-10', 'Financeiro', 'Em uso', 'Antônio José Dos Santos Silva', '2025-07-01', '3113.0', 'Novo - Financeiro 6', 'SPE MARA ROSA EMPREENDIMENTOS IMOBILIÁRIOS LTDA', NULL);
INSERT INTO equipamento (id_interno, id_publico, tipo, marca, modelo, num_serie, data_aquisicao, localizacao, status, responsavel, ultima_manutencao, valor, observacoes, SPE, termo_pdf_path) VALUES ('21', 'PAT-021', 'Notebook', 'Dell', 'Inspiron 15 3520', '9QZR194', '2025-06-16', 'Financeiro', 'Em uso', 'Susane Alves Da Silva', '2025-07-22', '3113.0', 'Novo - Financeiro 2', 'Terrano Rio verde', NULL);
INSERT INTO equipamento (id_interno, id_publico, tipo, marca, modelo, num_serie, data_aquisicao, localizacao, status, responsavel, ultima_manutencao, valor, observacoes, SPE, termo_pdf_path) VALUES ('22', 'PAT-022', 'Notebook', 'Dell', 'Inspiron 15 3530', '4LRJCD4', '2025-09-30', 'Marketing', 'Em uso', 'Diego Brito Vieira', '2025-10-07', '3636.53', 'Novo - Marketing 8', 'TERRANO DOM BOSCO', 'PAT-022.pdf');
INSERT INTO equipamento (id_interno, id_publico, tipo, marca, modelo, num_serie, data_aquisicao, localizacao, status, responsavel, ultima_manutencao, valor, observacoes, SPE, termo_pdf_path) VALUES ('23', 'PAT-023', 'Notebook', 'Dell', 'Inspiron 15 3530', 'BLRJCD4', '2025-09-30', 'Marketing', 'Em uso', 'Brendda Ewellyn Ribeiro Dos Santos', '2025-10-07', '3636.53', 'Novo - Marketing 9', 'SPE LARANJEIRAS EMPREENDIMENTOS', 'PAT-023.pdf');
INSERT INTO equipamento (id_interno, id_publico, tipo, marca, modelo, num_serie, data_aquisicao, localizacao, status, responsavel, ultima_manutencao, valor, observacoes, SPE, termo_pdf_path) VALUES ('24', 'PAT-024', 'Notebook', 'Dell', 'Inspiron 15 3530', 'FLRJCD4', '2025-09-30', 'Marketing', 'Em uso', 'Camila Rodrigues', '2025-10-08', '3636.53', 'Novo - Marketing 9', 'SPE LARANJEIRAS EMPREENDIMENTOS', 'PAT-024.pdf');

-- USUÁRIOS
INSERT INTO usuario (id, username, password_hash, nivel_acesso) VALUES ('1', 'admin', '$2b$12$0GGZIi9Vbah6EZX/nnXoXepNz5/CZQkr9XeXVis1a8LssOdlVMlRy', '3');
INSERT INTO usuario (id, username, password_hash, nivel_acesso) VALUES ('2', 'Carlos Magno', '$2b$12$QEd36XlyoiCrgc92ELjXA.Biav0KCgkV9I7gIkaGy/CuqOK5WORju', '3');
INSERT INTO usuario (id, username, password_hash, nivel_acesso) VALUES ('5', 'Diego', '$2b$12$KJPSdbxVR1nF2Bmq6z1QkOiXegPon3N8wDgLsp4IHKgO63vDiDMDK', '2');
INSERT INTO usuario (id, username, password_hash, nivel_acesso) VALUES ('4', 'Hanna', '$2b$12$EuVHkFYiVLMzhHnJupP9luA46SOijAhuyyg2jqmUx5V25Mp7UYjpa', '2');
