"""baseline

Revision ID: 44779d6d5169
Revises: 
Create Date: 2026-10-07 16:12:34.763943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44779d6d5169'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('icone', sa.String(length=50), nullable=True),
    sa.Column('cor', sa.String(length=7), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('fornecedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('endereco', sa.Text(), nullable=True),
    sa.Column('contato_principal', sa.String(length=200), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=120), nullable=False),
    sa.Column('nivel_acesso', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('nome_completo', sa.String(length=200), nullable=True),
    sa.Column('departamento', sa.String(length=100), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('equipamento',
    sa.Column('id_interno', sa.Integer(), nullable=False),
    sa.Column('id_publico', sa.String(length=20), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('modelo', sa.String(length=100), nullable=True),
    sa.Column('num_serie', sa.String(length=100), nullable=True),
    sa.Column('data_aquisicao', sa.Date(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('valor_residual', sa.Float(), nullable=True),
    sa.Column('vida_util_anos', sa.Integer(), nullable=True),
    sa.Column('valor_depreciado', sa.Float(), nullable=True),
    sa.Column('localizacao', sa.String(length=200), nullable=True),
    sa.Column('responsavel', sa.String(length=100), nullable=True),
    sa.Column('centro_custo', sa.String(length=100), nullable=True),
    sa.Column('departamento', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('condicao', sa.String(length=50), nullable=True),
    sa.Column('ultima_manutencao', sa.Date(), nullable=True),
    sa.Column('proxima_manutencao', sa.Date(), nullable=True),
    sa.Column('garantia_ate', sa.Date(), nullable=True),
    sa.Column('fornecedor_id', sa.Integer(), nullable=True),
    sa.Column('nota_fiscal', sa.String(length=100), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('subcategoria', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('codigo_barras', sa.String(length=100), nullable=True),
    sa.Column('qr_code', sa.Text(), nullable=True),
    sa.Column('rfid_tag', sa.String(length=100), nullable=True),
    sa.Column('imagem_url', sa.String(length=500), nullable=True),
    sa.Column('termo_pdf_path', sa.String(length=500), nullable=True),
    sa.Column('manual_url', sa.String(length=500), nullable=True),
    sa.Column('SPE', sa.String(length=50), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('especificacoes_tecnicas', sa.Text(), nullable=True),
    sa.Column('configuracao', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('bloqueado', sa.Boolean(), nullable=True),
    sa.Column('motivo_bloqueio', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedor.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id_interno'),
    sa.UniqueConstraint('codigo_barras'),
    sa.UniqueConstraint('id_publico'),
    sa.UniqueConstraint('num_serie'),
    sa.UniqueConstraint('rfid_tag')
    )
    op.create_table('historico_equipamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipamento_id', sa.Integer(), nullable=False),
    sa.Column('acao', sa.String(length=100), nullable=False),
    sa.Column('campo_alterado', sa.String(length=100), nullable=True),
    sa.Column('valor_anterior', sa.Text(), nullable=True),
    sa.Column('valor_novo', sa.Text(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data_acao', sa.DateTime(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['equipamento_id'], ['equipamento.id_interno'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manutencao_programada',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipamento_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('data_programada', sa.Date(), nullable=False),
    sa.Column('data_realizada', sa.Date(), nullable=True),
    sa.Column('responsavel_tecnico', sa.String(length=200), nullable=True),
    sa.Column('custo_estimado', sa.Float(), nullable=True),
    sa.Column('custo_real', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['equipamento_id'], ['equipamento.id_interno'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notificacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('lida', sa.Boolean(), nullable=True),
    sa.Column('link_acao', sa.String(length=200), nullable=True),
    sa.Column('equipamento_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('lida_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['equipamento_id'], ['equipamento.id_interno'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notificacao')
    op.drop_table('manutencao_programada')
    op.drop_table('historico_equipamento')
    op.drop_table('equipamento')
    op.drop_table('usuario')
    op.drop_table('fornecedor')
    op.drop_table('categoria')
    # ### end Alembic commands ###
