"""Add modernized database schema - categories, suppliers, history, notifications

Revision ID: 68f8c7f23741
Revises: 
Create Date: 2025-10-08 15:31:33.827303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68f8c7f23741'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipamento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valor_depreciado', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('departamento', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('condicao', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('proxima_manutencao', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('fornecedor_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('nota_fiscal', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('categoria_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('qr_code', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('rfid_tag', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('imagem_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('manual_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('especificacoes_tecnicas', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('configuracao', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ativo', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('bloqueado', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('motivo_bloqueio', sa.String(length=200), nullable=True))
        batch_op.alter_column('id_publico',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_unique_constraint('uq_equipamento_num_serie', ['num_serie'])
        batch_op.create_unique_constraint('uq_equipamento_codigo_barras', ['codigo_barras'])
        batch_op.create_unique_constraint('uq_equipamento_rfid_tag', ['rfid_tag'])
        batch_op.create_foreign_key('fk_equipamento_categoria', 'categoria', ['categoria_id'], ['id'])
        batch_op.create_foreign_key('fk_equipamento_fornecedor', 'fornecedor', ['fornecedor_id'], ['id'])
        batch_op.drop_column('categoria')
        batch_op.drop_column('fornecedor')

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('nome_completo', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('departamento', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('ativo', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('last_login')
        batch_op.drop_column('created_at')
        batch_op.drop_column('ativo')
        batch_op.drop_column('departamento')
        batch_op.drop_column('nome_completo')
        batch_op.drop_column('email')

    with op.batch_alter_table('equipamento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fornecedor', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('categoria', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint('fk_equipamento_fornecedor', type_='foreignkey')
        batch_op.drop_constraint('fk_equipamento_categoria', type_='foreignkey')
        batch_op.drop_constraint('uq_equipamento_rfid_tag', type_='unique')
        batch_op.drop_constraint('uq_equipamento_codigo_barras', type_='unique')
        batch_op.drop_constraint('uq_equipamento_num_serie', type_='unique')
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('id_publico',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('motivo_bloqueio')
        batch_op.drop_column('bloqueado')
        batch_op.drop_column('ativo')
        batch_op.drop_column('configuracao')
        batch_op.drop_column('especificacoes_tecnicas')
        batch_op.drop_column('manual_url')
        batch_op.drop_column('imagem_url')
        batch_op.drop_column('rfid_tag')
        batch_op.drop_column('qr_code')
        batch_op.drop_column('tags')
        batch_op.drop_column('categoria_id')
        batch_op.drop_column('nota_fiscal')
        batch_op.drop_column('fornecedor_id')
        batch_op.drop_column('proxima_manutencao')
        batch_op.drop_column('condicao')
        batch_op.drop_column('departamento')
        batch_op.drop_column('valor_depreciado')

    # ### end Alembic commands ###
