name: Deploy Flask to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout o código
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install pandas
        pip install -r requirements.txt

    - name: Verificar pacotes instalados
      run: pip freeze

    - name: Deploy no Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: terrano-backend
        slot-name: Production
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
