name: Deploy para Azure via Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build e push da imagem
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/terrano-backend-v2:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/terrano-backend-v2:latest

      - name: Login no Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy no Azure Web App
        uses: azure/webapps-container-deploy@v1
        with:
          app-name: terrano-backend-v2
          slot-name: production
          images: ${{ secrets.DOCKERHUB_USERNAME }}/terrano-backend-v2:latest
