name: Deploy Flask App via Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build e push da imagem Docker
        run: |
          docker build -t viniciuscrypto1/terrano-backend-v2:latest .
          docker push viniciuscrypto1/terrano-backend-v2:latest

      - name: Deploy no Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: terrano-backend-v2
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'viniciuscrypto1/terrano-backend-v2:latest'
