name: Deploy com Docker no Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build da imagem Docker
        run: |
          docker build -t viniciuscrypto1/terrano-backend-v2:latest .
          docker push viniciuscrypto1/terrano-backend-v2:latest

      - name: Deploy no Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: terrano-backend-v2
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: viniciuscrypto1/terrano-backend-v2:latest
